repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--check", "--diff"]
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: main
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - .
          - "--disable-error-code=import-untyped"
        additional_dependencies:
          - pydantic>=2
          - pydantic-settings>=2
          - fastapi>=0.110
          - sqlalchemy>=2
          - debugpy>=1.8.0
          - httpx>=0.25
          - types-requests
          - typing-extensions
          - weaviate-client>=4.7.0
          - asyncpg>=0.30.0
          - structlog>=25.4.0
          - alembic>=1.16.5
          - pytest>=8.4.2
          - pytest-asyncio>=1.2.0
          - dependency-injector>=4.48.2
          - langchain-aws>=1.0.0
          - langchain-community>=0.4.1
          - langchain-core>=1.0.4
          - langchain-weaviate>=0.0.6
          - langchain-openai>=1.0.2
          - advanced-chunker>=0.1.4
          - pypdf>=6.2.0
        exclude: .*/transformers/.*

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit
        pass_filenames: false
        args: ["-q", "-r", "src"]
